spring.application.name=heartsync

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/heartsyncdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=112233
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ????????? ??????????
spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=none
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration,\
  org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration,\
  org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration,\
  org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration

# Mailtrap SMTP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=05948e40cbb30a
spring.mail.password=cc98d83fdc9e35
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

